# app/config/routing.yml
prueba_index:
    path: /hola
    defaults: { _controller: AppBundle:Service:index }
prueba_user:
    path: /user
    defaults: { _controller: AppBundle:Service:user }
prueba_prueba:
    path: /
    defaults: { _controller: AppBundle:Service:cero }